### ISSUE TITLE
Tsumego ggg-hard-78

### ISSUE THREAD

**Issue by jdnewmil** [gogameguru/weekly-go-problems#2]
At move 7 Black self-ataris.

**Comment by yewang** [comment]
Which variation are you referring to? I would assume that you are talking about [this move](http://yewang.github.io/besogo/testing.html?theme=wood&realstones=on&sgf=https://raw.githubusercontent.com/gogameguru/go-problems/master/weekly-go-problems/hard/ggg-hard-78.sgf&path=4b2n2), since that appears to be the only move in the entire problem tree that is a self-atari for black. Is that right?

By playing that move, black initiates a ko fight, which he would need to win in order to obtain life for his group. This is not the optimal solution for this problem, since there are other paths where black can live outright, hence this variation is not marked as correct, but I believe it is included for instructional purposes. I don't see any issues with this problem.

**Comment by jdnewmil** [comment]
No, that was not the move, but I retract my comment. I somehow misread the board position.

**Comment by dormerod** [comment]
Thanks for sorting it out guys :)
